version: 2
jobs:
  rspec:
    docker:
      - image: ehdevops/ruby240:1.0.4
    working_directory: ~/google_json_response
    steps:
      - checkout
      - restore_cache:
          keys:
            - bundle-caches{{ checksum "Gemfile.lock" }}
      - run: bundle check || bundle install --path=vendor/bundle --jobs=4 --retry=3
      - save_cache:
          key: bundle-caches{{ checksum "Gemfile.lock" }}
          paths:
            - ~/google_json_response/vendor/bundle
      - run: mkdir -p tmp/; mkdir -p tmp/cache
      - run: bundle exec rspec
  publish:
    docker:
      - image: ehdevops/ruby240:1.0.4
    working_directory: ~/google_json_response
    steps:
      - checkout
      - restore_cache:
          keys:
            - bundle-caches{{ checksum "Gemfile.lock" }}
      - run: bundle check || bundle install --path=vendor/bundle --jobs=4 --retry=3
      - run: bundle exec ruby scripts/publish.rb

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - rspec
      - publish:
          context: org-global
          filters:
            branches:
              only: master
          requires:
            - rspec
